# Based on:
# https://gist.github.com/dan-blanchard/7045057
# https://github.com/Jorge-C/ordination/blob/master/.travis.yml
# https://github.com/soft-matter/trackpy/blob/master/.travis.yml
# http://conda.pydata.org/docs/travis.html

# See also: https://github.com/travis-ci/travis-ci/issues/2650

# Updated based on Travis-CI implementing improved python
# support and switching to xenial as default build environment
# https://docs.travis-ci.com/user/languages/python/
# https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  # Set up grunt by installing grunt-cli
  # and the dependencies listed in package.json
  - npm install -g grunt-cli
  - npm install

# Install packages
install:
  - pip install -U pip
  - pip install numpy>=1.16 scipy flake8 requests numpy-financial
  - pip install pandas>=2.2 flake8 requests pandas

# Run test(s)
script:
  - python3 -m unittest discover -p '*_test.py'
  - grunt travis -v
  - flake8 --exclude docs/conf.py --max-line-length=100