name: integration-tests
on: [workflow_call]
jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-0f57c48465f6361a6
          ec2-instance-type: r5a.4xlarge
          subnet-id: subnet-a4b769c3
          security-group-id: sg-06a2ae324a6e68d4d
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "scout-github-runner"},
              {"Key": "billingId", "Value": "210109"},
              {"Key": "org", "Value": "scout"}
            ]

  ecm-prep-job:
    name: Integration Testing ECM Prep
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.git
          key: ${{ runner.os }}-git-${{ github.sha }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . psrecord
      - name: Run and profile ecm_prep.py
        run: |
          branch_name="${{ github.ref }}"
          if [[ $branch_name == 'refs/heads/master' ]]; then
            psrecord --log memory_log_ecm_prep.txt --include-children --interval 1 "python tests/integration_testing/run_workflow.py --run_step ecm_prep --yaml tests/integration_testing/integration_test.yml --with_profiler"
            (echo -e; echo "# Elapsed time,CPU (%),Peak Real (MB),Peak Virtual (MB)"; grep -v "time" memory_log_ecm_prep.txt | sort -k3 -n -r | head -n 1 | column -t | tr -s '[:blank:]' ',') >> tests/integration_testing/results/profile_ecm_prep.csv
            mv memory_log_ecm_prep.txt ./tests/integration_testing/results/
          else
            python tests/integration_testing/run_workflow.py --run_step ecm_prep --yaml tests/integration_testing/integration_test.yml
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ./tests/integration_testing/results/

  run-job:
    name: Integration Testing Run
    needs: [start-runner, ecm-prep-job]
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.git
          key: ${{ runner.os }}-git-${{ github.sha }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          clean: false
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . psrecord
      - name: Run and profile run.py
        run: |
          branch_name="${{ github.ref }}"
          if [[ $branch_name == 'refs/heads/master' ]]; then
            psrecord --log memory_log_run.txt --include-children --interval 1 "python tests/integration_testing/run_workflow.py --run_step run --yaml tests/integration_testing/integration_test.yml --with_profiler"
            (echo -e; echo "# Elapsed time,CPU (%),Peak Real (MB),Peak Virtual (MB)"; grep -v "time" memory_log_run.txt | sort -k3 -n -r | head -n 1 | column -t | tr -s '[:blank:]' ',') >> tests/integration_testing/results/profile_run.csv
            mv memory_log_run.txt ./tests/integration_testing/results/
          else
            python tests/integration_testing/run_workflow.py --run_step run --yaml tests/integration_testing/integration_test.yml
          fi
          echo "Working directory $(pwd)"
          ls -la
          ls -la scout
          mv ./results/*.json ./tests/integration_testing/results/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ./tests/integration_testing/results/
      - name: Commit test results
        run: |
          branch_name="${{ github.ref }}"
          git pull origin $branch_name
          git add ./tests/integration_testing/results/*.json
          if [[ $(git diff --cached --exit-code) ]]; then
            git config --system user.email "github-action@users.noreply.github.com"
            git config --system user.name "GitHub Action"
            git commit -m "Upload results files from CI build"
            echo "Pushing to branch: $branch_name"
            git push -u origin $branch_name

            # Set status checks to success
            checks=("code-quality-checks" "python-tests (3.10)" "python-tests (3.11)" "python-tests (3.12)" "Integration Testing")
            commit_sha=$(git rev-parse HEAD)
            status_url="https://api.github.com/repos/${{ github.repository }}/statuses/$commit_sha"
            for check in "${checks[@]}"; do
              curl -L \
                -X POST \
                $status_url \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -d '{
                  "state": "success",
                  "context": "'"${check}"'",
                  "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }'
            done
          fi
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - ecm-prep-job
      - run-job
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}