name: integration-tests
on: [workflow_call]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy>=1.16 pandas>=2.2 scipy requests numpy-financial matplotlib xlsxwriter
      - name: Select measure subset
        run: |
          shopt -s extglob
          cd ecm_definitions/ && rm -f !("energyplus_data"|"package_ecms.json"|"Best Res. HPWH (EE+DF–FS).json"|"Best Com. Air Sealing (New).json") && cd ../
          echo "[]" > ecm_definitions/package_ecms.json 
      - name: Run workflow
        run: python tests/integration_testing/run_workflow.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ./results/*.json
      - name: Commit test results
        run: |
          branch_name="${{ github.head_ref }}"
          git pull origin $branch_name
          cp -r ./results/*.json ./tests/integration_testing
          git add ./tests/integration_testing/*.json
          if [[ $(git diff --cached --exit-code) ]]; then
            git config --global user.email "github-action@users.noreply.github.com"
            git config --global user.name "GitHub Action"
            git commit -m "Upload test results."
            echo "Pushing to branch: $branch_name"
            git push -u origin $branch_name
          fi