name: tests
on: [push]
jobs:

  code-quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Get contents from tip of branch on push
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
      - name: Install Node dependencies
        run: npm install
      - name: Check for valid JSON
        run: grunt jsonreview -v
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Check Python code quality
        run: flake8 --exclude docs/conf.py --max-line-length=100

  python-tests:
    runs-on: ubuntu-latest

    # Specify python versions to run
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10']

    steps:
      - name: Get contents from tip of branch on push
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy>=1.16 pandas>=2.2 scipy requests numpy-financial matplotlib
      - name: Run tests
        run: python -m unittest discover -p '*_test.py'

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy>=1.16 pandas>=2.2 scipy requests numpy-financial matplotlib
      - name: download csv shapes
        run: |
          curl https://zenodo.org/record/7763161/files/Latest_Com_Shapes.zip?download=1 -o ecm_definitions/energyplus_data/savings_shapes/Latest_Com_Shapes.zip
          curl https://zenodo.org/record/7763161/files/Latest_Res_Shapes.zip?download=1 -o ecm_definitions/energyplus_data/savings_shapes/Latest_Res_Shapes.zip
          unzip ecm_definitions/energyplus_data/savings_shapes/Latest_Com_Shapes.zip -d ecm_definitions/energyplus_data/savings_shapes
          unzip ecm_definitions/energyplus_data/savings_shapes/Latest_Res_Shapes.zip -d ecm_definitions/energyplus_data/savings_shapes
          mv ecm_definitions/energyplus_data/savings_shapes/Latest_Com_Shapes/* ecm_definitions/energyplus_data/savings_shapes
          mv ecm_definitions/energyplus_data/savings_shapes/Latest_Res_Shapes/* ecm_definitions/energyplus_data/savings_shapes
      - name: run ecm_prep.py
        run: printf 1| python ecm_prep.py --alt_regions      
      - name: run run.py
        run: python run.py 

